### ISSUE TITLE
Add config file to introduce specific mechanics to weapons and edit properties

### ISSUE THREAD

**Issue by Lucipo** [sf-inc/sihywtcamc#16]
If you want to use this mod in a pack that adds other weapons then all the vanilla weapons are instantly at a disadvantage due to rules like with a shield and axe. Little areas to put item id's to apply things like the axe + shield cooldowns would be great for compatibility

edit: please delete I was wrong about this right here it was compatible with modded axes and shields

**Comment by charlyb01** [comment]
For axe and shield, yes it should work as you said. For reach and modified attributes, I sadly can't do any config to allow people to modify other mods weapons: this is impossible unless I specifically write the compatibility in the code, which I couldn't do for every mods ;)
