### ISSUE TITLE
Bows can enchant with double enchantments, multiplying power

### ISSUE THREAD

**Issue by Lucipo** [sf-inc/sihywtcamc#17]
Simple, enchant a bow with level 30 (tested) and you will often get lots of duplicate enchantments on bows.
![image](https://user-images.githubusercontent.com/36358294/109619645-a5fc7680-7afe-11eb-88f0-f6d637b16591.png)
![image](https://user-images.githubusercontent.com/36358294/109619660-abf25780-7afe-11eb-965b-d61c0b4c7709.png)
![image](https://user-images.githubusercontent.com/36358294/109619733-bd3b6400-7afe-11eb-980c-119da81aa018.png)
![image](https://user-images.githubusercontent.com/36358294/109619747-c1678180-7afe-11eb-8d4c-978edd829d44.png)
Mod list on here: https://www.curseforge.com/minecraft/modpacks/neoteric-vanilla

**Comment by charlyb01** [comment]
Oh my bad! I added this bug when I added configs, oopsie. I'll fix that quickly =)

**Comment by charlyb01** [comment]
Even though I already solved the problem, I may not update the mod today but very soon don't worry

**Comment by charlyb01** [comment]
Didn't have time to add anything else so I published the fixed version. Sorry for the time I took

**Comment by Lucipo** [comment]
thanks :)
