### ISSUE TITLE
Feature Request: Config for adding modded tools

### ISSUE THREAD

**Issue by AzureMonument** [sf-inc/sihywtcamc#19]
I don't know how hard this would be too implement, but it would be nice to have the ability to add modded items to the mod through a config option, maybe somewhat like Project: War Dance (Though I think that may be a forge mod), and have the options for setting their percentage damage types, range, speed, etc.

**Comment by charlyb01** [comment]
I didn't want to add too much settings such as changing the values of stacks but as you ask I may add this on a future update.

For the modded weapons, this seem quite impossible but I just thought of something... Also it's a lot of config to setup and I already told about modded weapons that I won't do anything as it's impossible to configure globally BUT I just saif that I thought of something yeah? So I'll try this (even though it will be a struggle lol) but I can't tell you right now if it will possible: this is just an idea. Anyway, this will take some time to try so I'll let you know later. See you!

**Comment by charlyb01** [comment]
Okay, it seems it's not impossible. I'll make some tests but there is hope ;)
