### ISSUE TITLE
Missing config option for Shielding Creeper

### ISSUE THREAD

**Issue by Neubulae** [sf-inc/sihywtcamc#22]
In combat tests, shield 100% blocks explosion damages.

**Comment by charlyb01** [comment]
Thanks for the report! I didn't notice that putting the maximum amount of damage absorbtion would make the shield quite useless for explosions. And you're right, I didn't know explosions are fully cancelled when shielded in the snapshots =)
I will update this soon

**Comment by Neubulae** [comment]
hi

**Comment by charlyb01** [comment]
Sorry, I was working on something else for reach attribute and as I was not done with it, I didn't do this one. I'll do this first then, it shouldn't be too long to come

**Comment by charlyb01** [comment]
Alright, this shoud come very soon: I made the change. Just to tell you that it won't be a config but the default behavior as it's important ;)
