### ISSUE TITLE
Projectile blocking with shield

### ISSUE THREAD

**Issue by AzureMonument** [sf-inc/sihywtcamc#25]
I do not know if this is intended behavior- but I cannot for the life of me block skeleton projectiles with a shield? If this intended a config option to enable/disable this would be great. I'm running fabric 1.17.1, with sihywtcamc 1.3.1

**Comment by charlyb01** [comment]
This is an intended behavior that you can deactivate if you want. You actually still can block skeleton projectile, but now you need to aim the skeleton better than before. The arc protection of the shield was 180° and is now 120 (it's worst in combat snapshot, only 100°!). See [this](https://github.com/sf-inc/sihywtcamc/blob/main/CHANGELOG.md#v11)
