### ISSUE TITLE
Stackable Splash Potions in config

### ISSUE THREAD

**Issue by BreadBxsket** [sf-inc/sihywtcamc#26]
Could we get the ability to config being able to stack splash potions? The default stack could still be 1, but as a player you'd be able to config this if wanted.

**Comment by charlyb01** [comment]
I didn't change this on purporse because splash potions stackable would have been too broken to my mind.
However, I thought of something that may make it more balanced: stackable splash potions but it has a cooldown like ender pearls for example. What do you think about it?

**Comment by BreadBxsket** [comment]
a cooldown on stackable potions sounds like a great solution to the issue of balancing it, even if the cooldown is very long
