### ISSUE TITLE
The reach attribute doesn't work,

### ISSUE THREAD

**Issue by vlad1m** [sf-inc/sihywtcamc#32]
I set multiple custom ranges for both vanilla and modded tools,and these attributes are displayed in their tooltips,but in reality their range didn't change

**Comment by charlyb01** [comment]
Hello and thanks for the report. I will need some more informations like which Minecraft and mod version you're playing with. And also if you're playing with any other mod that could cause a compatibility issue.

**Comment by vlad1m** [comment]
Oh,i forgot that i wrote here,the issue was in the world itself ,somehow the world were i tested the mod corrupted itself and caused several issues,so the mod is completely fine :)

**Comment by charlyb01** [comment]
Well I'm glad everything is working! Enjoy playing Combat mod :)
