### ISSUE TITLE
Mod removes any damage

### ISSUE THREAD

**Issue by Emeraldedd** [sf-inc/sihywtcamc#35]

**Comment by charlyb01** [comment]
Hello and thanks for the report. I'd appreciate a bit more details, like for example the mod version.

When porting the mod to 1.20 minecraft version, I indeed had a damage issue, that had been fixed quite quickly in the v1.4.5 version of the mod. If you're playing with the v1.4.4 version, this is the bug

**Comment by charlyb01** [comment]
Without more information, I'll close the issue
